# -*- coding: utf-8 -*-
# utils/constants.py
# Physics constants from Gymnasium LunarLander

#%% Constants

FPS = 50
SCALE = 30.0
MAIN_ENGINE_POWER = 13.0
SIDE_ENGINE_POWER = 0.6
INITIAL_RANDOM = 1000.0
LANDER_POLY = [(-14, +17), (-17, 0), (-17, -10), (+17, -10), (+17, 0), (+14, +17)]
LEG_AWAY = 20
LEG_DOWN = 18
LEG_W, LEG_H = 2, 8
LEG_SPRING_TORQUE = 40
SIDE_ENGINE_HEIGHT = 14
SIDE_ENGINE_AWAY = 12
MAIN_ENGINE_Y_LOCATION = 4
VIEWPORT_W = 600
VIEWPORT_H = 400

# Cooperative constants
COOP_SUCCESS_THRESHOLD = 600
ZONE_PENALTY_SCALE = 0.75
ZONE_BONUS = 0.0
CONTACT_PENALTY = 0.25
STEP_PENALTY = 0.05
LANDER1_SPAWN_X_OFFSET = -3.0
LANDER2_SPAWN_X_OFFSET = +3.0

# Hover penalty
HOVER_WINDOW_SIZE = 10
HOVER_PROGRESS_THRESHOLD_X = 0.005
HOVER_PROGRESS_THRESHOLD_Y = 0.01
HOVER_BASE_PENALTY = 0.05
HOVER_PENALTY_EXPONENT = 1.0
HOVER_MAX_PENALTY = 0.5
HOVER_MIN_ALTITUDE = 0.4
HOVER_COUNTER_DECAY = 1
HOVER_ACTIVATION_STEP = 600
HOVER_ESCALATION_STEP = 800
HOVER_ESCALATION_MULTIPLIER = 2.0

# Distance-to-zone progress bonus at hover milestones
# Bonus = scale * (prev_dist - curr_dist) when closing distance after milestone
PROGRESS_BONUS_SCALE_TIER1 = 20.0   # Active at step >= HOVER_ACTIVATION_STEP (600)
PROGRESS_BONUS_SCALE_TIER2 = 80.0   # Active at step >= HOVER_ESCALATION_STEP (800)

#%% End of Script
